# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=150)),
                ('company_state', models.IntegerField(null=True)),
                ('company_city', models.CharField(default='', max_length=150)),
                ('company_mission', models.TextField(blank=True, verbose_name="Company's mission statement")),
                ('current_stage', models.IntegerField(default=1, null=True)),
                ('locations_interested', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'AL'), (2, 'AK'), (3, 'AZ'), (4, 'AR'), (5, 'CA'), (6, 'CO'), (7, 'CT'), (8, 'DC'), (9, 'DE'), (10, 'FL'), (11, 'GA'), (12, 'HI'), (13, 'ID'), (14, 'IL'), (15, 'IN'), (16, 'IA'), (17, 'KS'), (18, 'KY'), (19, 'LA'), (20, 'ME'), (21, 'MD'), (22, 'MA'), (23, 'MI'), (24, 'MN'), (25, 'MS'), (26, 'MO'), (27, 'MT'), (28, 'NE'), (29, 'NV'), (30, 'NH'), (31, 'NJ'), (32, 'NM'), (33, 'NY'), (34, 'NC'), (35, 'ND'), (36, 'OH'), (37, 'OK'), (38, 'OR'), (39, 'PA'), (40, 'RI'), (41, 'SC'), (42, 'SD'), (43, 'TN'), (44, 'TX'), (45, 'UT'), (46, 'VT'), (47, 'VA'), (48, 'WA'), (49, 'WV'), (50, 'WI'), (51, 'WY')], max_length=143)),
                ('check_size', models.IntegerField(default=1, null=True)),
                ('sector', models.IntegerField(default=1, null=True)),
                ('other', models.TextField(blank=True, verbose_name='Previous investors, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='VentureCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=150)),
                ('company_state', models.IntegerField(default=1, null=True)),
                ('company_city', models.CharField(default='', max_length=120)),
                ('company_mission', models.TextField(blank=True, verbose_name='Mission statement of the company.')),
                ('company_fund_size', models.IntegerField(default=1, null=True)),
                ('stages_interested', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Pre-Seed'), (2, 'Seed'), (3, 'Series A'), (4, 'Series B'), (5, 'Series C/Growth')], max_length=9)),
                ('stages_avoid', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Pre-Seed'), (2, 'Seed'), (3, 'Series A'), (4, 'Series B'), (5, 'Series C/Growth')], max_length=9)),
                ('locations_interested', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'AL'), (2, 'AK'), (3, 'AZ'), (4, 'AR'), (5, 'CA'), (6, 'CO'), (7, 'CT'), (8, 'DC'), (9, 'DE'), (10, 'FL'), (11, 'GA'), (12, 'HI'), (13, 'ID'), (14, 'IL'), (15, 'IN'), (16, 'IA'), (17, 'KS'), (18, 'KY'), (19, 'LA'), (20, 'ME'), (21, 'MD'), (22, 'MA'), (23, 'MI'), (24, 'MN'), (25, 'MS'), (26, 'MO'), (27, 'MT'), (28, 'NE'), (29, 'NV'), (30, 'NH'), (31, 'NJ'), (32, 'NM'), (33, 'NY'), (34, 'NC'), (35, 'ND'), (36, 'OH'), (37, 'OK'), (38, 'OR'), (39, 'PA'), (40, 'RI'), (41, 'SC'), (42, 'SD'), (43, 'TN'), (44, 'TX'), (45, 'UT'), (46, 'VT'), (47, 'VA'), (48, 'WA'), (49, 'WV'), (50, 'WI'), (51, 'WY')], max_length=143)),
                ('locations_avoid', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'AL'), (2, 'AK'), (3, 'AZ'), (4, 'AR'), (5, 'CA'), (6, 'CO'), (7, 'CT'), (8, 'DC'), (9, 'DE'), (10, 'FL'), (11, 'GA'), (12, 'HI'), (13, 'ID'), (14, 'IL'), (15, 'IN'), (16, 'IA'), (17, 'KS'), (18, 'KY'), (19, 'LA'), (20, 'ME'), (21, 'MD'), (22, 'MA'), (23, 'MI'), (24, 'MN'), (25, 'MS'), (26, 'MO'), (27, 'MT'), (28, 'NE'), (29, 'NV'), (30, 'NH'), (31, 'NJ'), (32, 'NM'), (33, 'NY'), (34, 'NC'), (35, 'ND'), (36, 'OH'), (37, 'OK'), (38, 'OR'), (39, 'PA'), (40, 'RI'), (41, 'SC'), (42, 'SD'), (43, 'TN'), (44, 'TX'), (45, 'UT'), (46, 'VT'), (47, 'VA'), (48, 'WA'), (49, 'WV'), (50, 'WI'), (51, 'WY')], max_length=143)),
                ('sectors_interested', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'AI/ML/Cloud'), (2, 'Cryptocurrency/Blockchaim'), (3, 'Technology'), (4, 'Pharmacy'), (5, 'Market Places'), (6, 'Real Estate'), (7, 'Robotics/Drones'), (8, 'Security'), (9, 'Infrastructure/Transportation'), (10, 'E-Commerce'), (11, 'Human Resources'), (12, 'Consumers'), (13, 'Entertainment'), (14, 'Mobile'), (15, 'Data Analytics'), (16, 'Developer Tools'), (17, 'Marketing'), (18, 'Enterprises'), (19, 'Wearables')], max_length=47)),
                ('sectors_avoid', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'AI/ML/Cloud'), (2, 'Cryptocurrency/Blockchaim'), (3, 'Technology'), (4, 'Pharmacy'), (5, 'Market Places'), (6, 'Real Estate'), (7, 'Robotics/Drones'), (8, 'Security'), (9, 'Infrastructure/Transportation'), (10, 'E-Commerce'), (11, 'Human Resources'), (12, 'Consumers'), (13, 'Entertainment'), (14, 'Mobile'), (15, 'Data Analytics'), (16, 'Developer Tools'), (17, 'Marketing'), (18, 'Enterprises'), (19, 'Wearables')], max_length=47)),
                ('check_size', models.IntegerField(default=1, null=True)),
                ('previous_investments', models.TextField(blank=True, verbose_name='Previous investments.')),
            ],
        ),
    ]
