# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField()),
                ('entrepreneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Entrepreneur')),
                ('venturecapital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.VentureCapital')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together=set([('entrepreneur', 'venturecapital')]),
        ),
    ]
